const AdminUsersActionTypes = {
  SET_ADMIN_USERS_DATA: "SET_ADMIN_USERS_DATA",
  SET_ADMIN_USERS_PARAMS: "SET_ADMIN_USERS_PARAMS",
  SET_ADMIN_USERS_SINGLE: "SET_ADMIN_USERS_SINGLE",
  SET_ADMIN_USERS_SINGLE_UPDATED: "SET_ADMIN_USERS_SINGLE_UPDATED",
  SET_ADMIN_USERS_SINGLE_EMPTY: "SET_ADMIN_USERS_SINGLE_EMPTY"
};

export default AdminUsersActionTypes;
